### ISSUE TITLE
Extension to multiple clusters

### ISSUE THREAD

**Issue by zaemyung** [nodrogluap/OpenDBA#10] opened 2021-02-24 16:10 UTC
I was wondering if running of the OpenDBA assumes that the sequences are inherently (more or less) similar to each other, meaning that they can be averaged to a single cluster.
In my scenario, I have a large number of sequences that should be grouped into more than one cluster.
Would running the OpenDBA and using the `output_prefix.pair_dists.txt` distances be applicable in this case?
```R
  tab <- read.table("foo.pair_dists.txt", sep="\t", row.names=1, header=FALSE)
  colnames(tab) <- rownames(tab)
  dis <- as.dist(t(tab), diag=TRUE)
  hc <- hclust(dis)
  plot(hc)
```
Or should it need to be extended to do k-mean clustering as in https://tslearn.readthedocs.io/en/stable/auto_examples/clustering/plot_kmeans.html ?

**Comment by nodrogluap** [comment] 2021-02-24 17:05
Hi,

If you know the value of K a priori, yes k-means clustering makes sense.  There are many cluster generation algorithms you could use on the pair_dists.txt file, but none are built into OpenDBA currently.  I'm leaning towards Ensemble Clustering for Graphs (which is implemented in the NVIDIA RAPIDS AI package).  I'm going to count this as a duplicate of issue #8.

**Closed as completed** 2021-02-24 17:05 UTC
